version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "02:00"
      open-pull-requests-limit: 0
      commit-message:
        prefix: "ci: "
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "02:00"
      open-pull-requests-limit: 0
      commit-message:
        prefix: "ci: "
