- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"
- name: "dependencies"
  color: "0366d6"
  description: "Pull requests that update a dependency file"
- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"
- name: "duplicate"
  color: "cfd8d7"
  description: "This issue or pull request already exists"
- name: "enhancement"
  color: "a22eef"
  description: "New feature or request"
- name: "github_actions"
  color: "000000"
  description: "Pull requests that update GitHub Actions code"
- name: "help_wanted"
  color: "008672"
  description: "Extra attention is needed"
- name: "javascript"
  color: "168700"
  description: "Pull requests that update Javascript code"
- name: "refactor"
  description: "Rewrite existing logic"
  color: "00ff00"
- name: "question"
  color: "d876e3"
  description: "Further information is requested"
- name: "triage"
  color: "9B6C5B"
  description: "Conduct a preliminary assessment of issue"
- name: "wontfix_it"
  color: "ffffff"
  description: "This will not be worked on"
  from_name: "wontfix"