name: Create a comment on new issues

on:
  issues:
    types: [opened]

jobs:
  comment-with-api:
    runs-on: ubuntu-latest
    steps: 
      - name: Create comment with API
        run: |
          gh api -X POST \
            https://api.github.com/repos/${REPOSITORY_OWNER}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
            -f body='
            Comment but from the API call not action
            '
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPOSITORY_OWNER: ${{ github.repository_owner }}
      RPOSITORY: ${{ github.events.repository.name }}
      ISSUE_NUMBER: ${{ github.events.issue.number }}
      
      


