name: Create a comment on new issues

on:
  issues:
    types: [opened]

jobs:
  comment-with-api:
    runs-on: ubuntu-latest
    steps: 
      - name: Create comment with API
        run: echo https://api.github.com/repos/${REPOSITORY_OWNER}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments
            
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPOSITORY_OWNER: ${{ github.event.repository.owner.login }}
      RPOSITORY: ${{ github.event.repository.name }}
      ISSUE_NUMBER: ${{ github.event.issue.number }}
      
      


