name: Automatically create / update pull request

# run this workflow only on new feature branches, not when they're merged to main
on:
  push:
    branches-ignore:
      - development

jobs:
  create_pr_repo_sync:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          base: development
          title: "feat: PLACEHOLDER TITLE"
          body-path: ".github/PULL_REQUEST_TEMPLATE.md"
          # pr_reviewer: "johndoe"
          draft: true