name: Check PR Label

on:
  pull_request:
    types: 
      - opened
      - labeled
      - unlabeled
      - edited
      - synchronize
    branches: 
      - development

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
    - name: Check if PR has the required labels
      id: check_label
      run: |
        # Get the list of labels
        labels=$(jq -r '.pull_request.labels[].name' "$GITHUB_EVENT_PATH")

        # Check if any of the labels are bug, enhancement, or refactor
        if echo "$labels" | grep -Eq '^(bug|enhancement|refactor)$'; then
          echo "PR has one of the required labels."
          echo "label_valid=true" >> "$GITHUB_OUTPUT"
        else
          echo "PR is missing the required labels."
          echo "label_valid=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Fail if PR does not have the required labels
      if: steps.check_label.outputs.label_valid == 'false'
      run: |
        echo "This PR is missing one of the required labels: bug, enhancement, or refactor."
        exit 1
