name: Check PR Label and Update PR Description

on:
  pull_request:
    types: 
      - opened
      - labeled
      - unlabeled
      - edited
      - synchronize
    branches: 
      - development

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
    - name: Set required labels
      run: |
        echo "REQUIRED_LABELS=bug|enhancement|refactor" >> $GITHUB_ENV

    - name: Check if PR has the required labels
      id: check_label
      run: |
        # Get the list of labels
        labels=$(jq -r '.pull_request.labels[].name' "$GITHUB_EVENT_PATH")

        # Check if any of the labels match the required ones
        if echo "$labels" | grep -Eq "($REQUIRED_LABELS)"; then
          echo "PR has one of the required labels."
          echo "label_valid=true" >> "$GITHUB_OUTPUT"
        else
          echo "PR is missing the required labels."
          echo "label_valid=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Fail if PR does not have the required labels
      if: steps.check_label.outputs.label_valid == 'false'
      run: |
        echo "This PR is missing one of the required labels: bug, enhancement, or refactor."
        exit 1

    - name: Update PR description to check "Added label" box
      if: steps.check_label.outputs.label_valid == 'true'
      uses: actions/github-script@v6
      with:
        script: |
          const { owner, repo } = context.repo;
          const prNumber = context.payload.pull_request.number;
            
          // Get the current PR body
          const { data: pr } = await github.pulls.get({
            owner,
            repo,
            pull_number: prNumber,
          });

          const updatedBody = pr.body.replace('- [ ] Added label', '- [x] Added label');

          // Update the PR description
          await github.pulls.update({
            owner,
            repo,
            pull_number: prNumber,
            body: updatedBody,
          });
