name: Super Linter

on:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  build:
    name: Super Linter
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - name: Checkout code
        if: github.actor != 'dependabot[bot]'
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Super-linter
        if: github.actor != 'dependabot[bot]'
        uses: super-linter/super-linter@v6.8.0 # x-release-please-version
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
